
services:
  app:
    build:
      context: .
    image: sahityotsav-app
    volumes:
      - .:/app
      - prisma_db:/app/prisma  # Volume for SQLite database

volumes:
  prisma_db:
    driver: local